name: some-actions

on:
  push:
  pull_request:
    types:
      - opened


jobs:
  check:
    runs-on: ubuntu-latest
    name: Get Python and print
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: actions/checkout@v3
      - name: "Test print"
        run: echo github.event.action
      - name: "When pushed"
        if: github.event.action != 'opened'
        run: echo "MAIN"
      - name: "When opened"
        if: github.event.action == 'opened'
        run: echo "OPENED"
