name: some-actions

on:
  push:
  pull_request:
    types:
      - opened


jobs:
  check:
    runs-on: ubuntu-latest
    name: Get Python and print
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3
      - name: "When a pushe happened"
        if: github.event_name == 'push'
        run: echo "MAIN"
      - name: "When PR opened"
        if: github.event_name == 'pull_request'
        run: echo "OPENED"
