name: some-actions

on:
  push:
  pull_request:
    types:
      - opened


jobs:
  check:
    runs-on: ubuntu-latest
    name: Get Python and print
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3
      - name: "When pushed"
        if: github.event.action != 'opened'
        run: echo "MAIN"
      - name: "When opened"
        if: github.event.action == 'opened'
        run: echo "OPENED"
